# Generated by Django 6.0.5 on 2026-05-10 16:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bfd_monitor', '0001_initial'),
        ('equipements', '0001_initial'),
        ('snmp_collector', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('webhook', 'Webhook')], max_length=10)),
                ('configuration', models.JSONField(default=dict, help_text="{'url': '...', 'recipients': [...], 'headers': {...}}")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'alerting_notification_channels',
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('snmp', 'SNMP'), ('bfd', 'BFD'), ('ai', 'IA'), ('custom', 'Personnalisé')], max_length=10)),
                ('ai_severity_min', models.CharField(blank=True, help_text='Severité minimale IA (low/medium/high/critical)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('cooldown_minutes', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('message_template', models.TextField(help_text='Template avec variables {olt}, {value}, {severity}, {source}')),
                ('deduplication_window_minutes', models.IntegerField(default=5, help_text='Fenêtre de déduplication (0 = désactivée)')),
                ('bfd_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bfd_monitor.bfdthresholdrule')),
                ('snmp_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snmp_collector.snmpthresholdrule')),
            ],
            options={
                'db_table': 'alerting_rules',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.CharField(blank=True, db_index=True, help_text='ID dans la source (ex: snmp_alert_id)', max_length=100)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('major', 'Majeure'), ('critical', 'Critique')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acquittée'), ('resolved', 'Résolue')], db_index=True, default='active', max_length=20)),
                ('message', models.TextField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('olt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.olt')),
                ('ont', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.ont')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alerting.alertrule')),
            ],
            options={
                'db_table': 'alerting_alerts',
                'ordering': ['-first_seen'],
            },
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('success', models.BooleanField(default=True)),
                ('response', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerting.alert')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alerting.notificationchannel')),
            ],
            options={
                'db_table': 'alerting_notification_history',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['olt', 'status'], name='alerting_al_olt_id_1c1842_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='alerting_al_severit_34311b_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['source_id', 'rule'], name='alerting_al_source__a633f6_idx'),
        ),
    ]
