# Generated by Django 6.0.5 on 2026-05-10 16:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Clé')),
                ('value', models.JSONField(default=dict, verbose_name='Valeur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('config_type', models.CharField(choices=[('general', '⚙️ Général'), ('security', '🛡️ Sécurité / Authentification'), ('snmp', '📊 SNMP (polling, communautés, OIDs)'), ('bfd', '🔗 BFD (intervalles, multiplicateur)'), ('alerting', '🚨 Alertes (seuils, notifications)'), ('ai_engine', '🧠 IA / ML (modèles, seuils anomalie)'), ('eve_ng', '🧪 EVE-NG (intégration lab virtuel)'), ('notifications', '🔔 Notifications (email, webhook)'), ('exports', '📁 Exports de données (CSV, PDF)'), ('logs', '📜 Journalisation et rétention')], db_index=True, default='general', max_length=20, verbose_name='Type')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='Chiffré')),
            ],
            options={
                'verbose_name': 'Configuration IntelliOLT',
                'verbose_name_plural': 'Configurations IntelliOLT',
                'db_table': 'core_config',
                'indexes': [models.Index(fields=['key'], name='core_config_key_2bfab5_idx'), models.Index(fields=['config_type'], name='core_config_config__93d50e_idx')],
            },
        ),
    ]
