# Generated by Django 6.0.5 on 2026-05-10 16:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BFDThresholdRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la règle')),
                ('metric', models.CharField(choices=[('loss_rate', 'Taux de perte (%)'), ('detect_time', 'Temps de détection (ms)'), ('flap_rate', 'Taux de flapping (%)'), ('availability', 'Disponibilité (%)'), ('state_down', "Changement d'état vers DOWN")], max_length=20, verbose_name='Métrique surveillée')),
                ('operator', models.CharField(choices=[('>', '>'), ('<', '<'), ('=', '='), ('>=', '>='), ('<=', '<=')], default='>', max_length=2)),
                ('threshold', models.FloatField(verbose_name='Seuil')),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('message', models.CharField(max_length=255, verbose_name="Message d'alerte")),
                ('is_active', models.BooleanField(default=True)),
                ('cooldown_minutes', models.IntegerField(default=10, help_text='Délai avant ré-émission')),
            ],
            options={
                'db_table': 'bfd_threshold_rules',
                'ordering': ['severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BFDPollingSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poll_interval_seconds', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('olt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bfd_schedule', to='equipements.olt')),
            ],
            options={
                'db_table': 'bfd_polling_schedules',
            },
        ),
        migrations.CreateModel(
            name='BFDSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la session')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('peer_ip', models.GenericIPAddressField(blank=True, help_text='IP du pair BFD', null=True)),
                ('local_ip', models.GenericIPAddressField(blank=True, help_text='IP locale BFD', null=True)),
                ('vrf', models.CharField(blank=True, max_length=50, verbose_name='VRF')),
                ('local_discriminator', models.BigIntegerField(unique=True, verbose_name='Discriminateur local')),
                ('remote_discriminator', models.BigIntegerField(default=0, verbose_name='Discriminateur distant')),
                ('session_type', models.CharField(choices=[('single_hop', 'Single Hop'), ('multi_hop', 'Multi Hop'), ('echo', 'Echo')], default='single_hop', max_length=15, verbose_name='Type de session')),
                ('desired_tx_interval_ms', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Intervalle TX souhaité (ms)')),
                ('required_rx_interval_ms', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Intervalle RX requis (ms)')),
                ('detection_multiplier', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(50)], verbose_name='Multiplicateur de détection')),
                ('actual_tx_interval_ms', models.IntegerField(blank=True, null=True, verbose_name='Intervalle TX négocié (ms)')),
                ('actual_rx_interval_ms', models.IntegerField(blank=True, null=True, verbose_name='Intervalle RX négocié (ms)')),
                ('state', models.CharField(choices=[('up', '✅ UP'), ('down', '🔴 DOWN'), ('init', '🟡 INIT'), ('admin_down', '⚫ Admin Down')], db_index=True, default='down', max_length=15, verbose_name='État BFD')),
                ('diagnostic', models.IntegerField(choices=[(0, 'Aucun diagnostic'), (1, 'Délai de détection expiré'), (2, 'Fonction Echo en échec'), (3, 'Session voisine signalée DOWN'), (4, 'Réinitialisation du plan de forwarding'), (5, 'Chemin en panne'), (6, 'Chemin concaténé en panne'), (7, 'Administrativement DOWN'), (8, 'Chemin concaténé inverse en panne')], default=0, verbose_name='Code diagnostic')),
                ('last_state_change', models.DateTimeField(blank=True, null=True, verbose_name="Dernier changement d'état")),
                ('uptime_seconds', models.BigIntegerField(blank=True, null=True, verbose_name='Uptime (secondes)')),
                ('remote_state', models.CharField(blank=True, choices=[('up', '✅ UP'), ('down', '🔴 DOWN'), ('init', '🟡 INIT'), ('admin_down', '⚫ Admin Down')], max_length=15, null=True, verbose_name='État distant')),
                ('packets_sent', models.BigIntegerField(default=0, verbose_name='Paquets envoyés')),
                ('packets_received', models.BigIntegerField(default=0, verbose_name='Paquets reçus')),
                ('packets_lost', models.BigIntegerField(default=0, verbose_name='Paquets perdus')),
                ('loss_rate_pct', models.FloatField(default=0.0, verbose_name='Taux de perte (%)')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('up_count', models.IntegerField(default=0, verbose_name='Nombre de fois UP')),
                ('down_count', models.IntegerField(default=0, verbose_name='Nombre de fois DOWN')),
                ('flap_count', models.IntegerField(default=0, verbose_name='Nombre de flapping')),
                ('last_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier passage UP')),
                ('last_down_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier passage DOWN')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Session active')),
                ('is_monitored', models.BooleanField(default=True, verbose_name='Surveillée')),
                ('snmp_oid_state', models.CharField(blank=True, max_length=200, verbose_name='OID SNMP optionnel')),
                ('interface_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bfd_sessions_a', to='equipements.networkinterface', verbose_name='Interface A')),
                ('interface_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bfd_sessions_b', to='equipements.networkinterface', verbose_name='Interface B')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bfd_sessions', to='equipements.fibrelink', verbose_name='Lien fibre associé')),
                ('olt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bfd_sessions', to='equipements.olt', verbose_name='OLT (pour session directe)')),
            ],
            options={
                'db_table': 'bfd_sessions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BFDStateHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_state', models.CharField(choices=[('up', '✅ UP'), ('down', '🔴 DOWN'), ('init', '🟡 INIT'), ('admin_down', '⚫ Admin Down')], max_length=15)),
                ('new_state', models.CharField(choices=[('up', '✅ UP'), ('down', '🔴 DOWN'), ('init', '🟡 INIT'), ('admin_down', '⚫ Admin Down')], max_length=15)),
                ('diagnostic', models.IntegerField(choices=[(0, 'Aucun diagnostic'), (1, 'Délai de détection expiré'), (2, 'Fonction Echo en échec'), (3, 'Session voisine signalée DOWN'), (4, 'Réinitialisation du plan de forwarding'), (5, 'Chemin en panne'), (6, 'Chemin concaténé en panne'), (7, 'Administrativement DOWN'), (8, 'Chemin concaténé inverse en panne')], default=0)),
                ('duration_previous_ms', models.BigIntegerField(blank=True, help_text="Durée de l'état précédent en ms", null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('triggered_alert', models.BooleanField(default=False, help_text='A déclenché une alerte ?')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bfd_monitor.bfdsession')),
            ],
            options={
                'db_table': 'bfd_state_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BFDActiveAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField(blank=True, null=True, verbose_name="Valeur ayant déclenché l'alerte")),
                ('message', models.TextField(verbose_name="Message d'alerte")),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acquittée'), ('resolved', 'Résolue')], db_index=True, default='active', max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='bfd_monitor.bfdsession')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='bfd_monitor.bfdthresholdrule')),
            ],
            options={
                'db_table': 'bfd_alerts',
                'ordering': ['-first_seen'],
            },
        ),
        migrations.AddIndex(
            model_name='bfdsession',
            index=models.Index(fields=['state'], name='bfd_session_state_91fee7_idx'),
        ),
        migrations.AddIndex(
            model_name='bfdsession',
            index=models.Index(fields=['link'], name='bfd_session_link_id_47dada_idx'),
        ),
        migrations.AddIndex(
            model_name='bfdsession',
            index=models.Index(fields=['olt'], name='bfd_session_olt_id_a3390e_idx'),
        ),
        migrations.AddIndex(
            model_name='bfdsession',
            index=models.Index(fields=['interface_a', 'interface_b'], name='bfd_session_interfa_f9d506_idx'),
        ),
        migrations.AddIndex(
            model_name='bfdstatehistory',
            index=models.Index(fields=['session', '-timestamp'], name='bfd_state_h_session_c1c59d_idx'),
        ),
        migrations.AddIndex(
            model_name='bfdactivealert',
            index=models.Index(fields=['session', 'status'], name='bfd_alerts_session_e676be_idx'),
        ),
    ]
