// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/30/2026, 10:32:10 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/user/IntelliOLT/IntelliOLT_frontend_vue/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/IntelliOLT/IntelliOLT_frontend_vue/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/IntelliOLT/IntelliOLT_frontend_vue/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/IntelliOLT/IntelliOLT_frontend_vue/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/IntelliOLT/IntelliOLT_frontend_vue/plugins/**/*.{js,ts,mjs}","/home/user/IntelliOLT/IntelliOLT_frontend_vue/composables/**/*.{js,ts,mjs}","/home/user/IntelliOLT/IntelliOLT_frontend_vue/utils/**/*.{js,ts,mjs}","/home/user/IntelliOLT/IntelliOLT_frontend_vue/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/IntelliOLT/IntelliOLT_frontend_vue/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/user/IntelliOLT/IntelliOLT_frontend_vue/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/user/IntelliOLT/IntelliOLT_frontend_vue/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;