# Generated by Django 6.0.5 on 2026-05-10 16:42

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('timeout_seconds', models.FloatField(default=2.0, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('retries', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('bulk_max_repetitions', models.IntegerField(default=10, help_text="Nombre max d'OIDs par requête GETBULK")),
                ('is_default', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'snmp_polling_profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sys_object_id', models.CharField(blank=True, help_text='SysObjectID SNMP pour identification auto', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_profiles', to='equipements.devicetype')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_profiles', to='equipements.vendor')),
                ('polling_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_profiles', to='snmp_collector.pollingprofile')),
            ],
            options={
                'db_table': 'snmp_device_profiles',
                'ordering': ['vendor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SnmpOID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('oid', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('data_type', models.CharField(choices=[('integer', 'Entier'), ('counter', 'Compteur'), ('gauge', 'Jauge'), ('timeticks', 'TimeTicks'), ('string', 'Chaîne'), ('ip_address', 'Adresse IP'), ('oid', 'OID')], default='integer', max_length=20)),
                ('scale_factor', models.FloatField(default=1.0, help_text='Multiplicateur appliqué à la valeur brute.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'snmp_oids',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['oid'], name='snmp_oids_oid_9aaf95_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_value', models.TextField(blank=True)),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('gpon_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.gponport')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.networkinterface')),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='equipements.olt')),
                ('ont', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.ont')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snmp_collector.snmpoid')),
            ],
            options={
                'db_table': 'metric_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SnmpThresholdRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('operator', models.CharField(choices=[('>', '>'), ('<', '<'), ('>=', '>='), ('<=', '<='), ('=', '='), ('!=', '!=')], max_length=2)),
                ('threshold', models.FloatField()),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('cooldown_minutes', models.IntegerField(default=10, help_text='Délai avant de ré-émettre la même alerte')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_rules', to='snmp_collector.snmpoid')),
            ],
            options={
                'db_table': 'snmp_threshold_rules',
                'ordering': ['severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SnmpAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField()),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acquittée'), ('resolved', 'Résolue')], db_index=True, default='active', max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snmp_collector.metrichistory')),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipements.olt')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='snmp_collector.snmpthresholdrule')),
            ],
            options={
                'db_table': 'snmp_alerts',
                'ordering': ['-first_seen'],
            },
        ),
        migrations.CreateModel(
            name='PollJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('success', 'Succès'), ('partial', 'Partiel'), ('failed', 'Échec')], db_index=True, default='pending', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('metrics_collected', models.IntegerField(default=0)),
                ('metrics_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('lock_key', models.CharField(blank=True, max_length=100)),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_jobs', to='equipements.olt')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmp_collector.pollingprofile')),
            ],
            options={
                'db_table': 'poll_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['olt', '-created_at'], name='poll_jobs_olt_id_1c5b0d_idx'), models.Index(fields=['state'], name='poll_jobs_state_4be4aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='SnmpErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_type', models.CharField(choices=[('timeout', 'Timeout'), ('no_such_name', 'No Such Name'), ('auth_failure', 'Authentication Failure'), ('parse_error', 'Parse Error'), ('other', 'Other')], max_length=50)),
                ('error_message', models.TextField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved', models.BooleanField(default=False)),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_errors', to='equipements.olt')),
                ('oid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmp_collector.snmpoid')),
            ],
            options={
                'db_table': 'snmp_error_logs',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['olt', 'occurred_at'], name='snmp_error__olt_id_02d272_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileOID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_critical', models.BooleanField(default=False, help_text='Si True, la collecte de cet OID est obligatoire')),
                ('order', models.IntegerField(default=0, help_text='Ordre de collecte')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_oids', to='snmp_collector.deviceprofile')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_oids', to='snmp_collector.snmpoid')),
            ],
            options={
                'db_table': 'snmp_profile_oids',
                'ordering': ['profile', 'order'],
                'unique_together': {('profile', 'oid')},
            },
        ),
        migrations.AddIndex(
            model_name='metrichistory',
            index=models.Index(fields=['olt', 'oid', '-timestamp'], name='metric_hist_olt_id_277a95_idx'),
        ),
        migrations.AddIndex(
            model_name='metrichistory',
            index=models.Index(fields=['oid', '-timestamp'], name='metric_hist_oid_id_ee5eef_idx'),
        ),
        migrations.AddIndex(
            model_name='metrichistory',
            index=models.Index(fields=['interface', '-timestamp'], name='metric_hist_interfa_e9b4af_idx'),
        ),
        migrations.AddIndex(
            model_name='metrichistory',
            index=models.Index(fields=['ont', '-timestamp'], name='metric_hist_ont_id_04c330_idx'),
        ),
        migrations.AddIndex(
            model_name='metrichistory',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['timestamp'], name='metric_hist_timesta_73b44b_brin'),
        ),
        migrations.AddIndex(
            model_name='snmpalert',
            index=models.Index(fields=['olt', 'status'], name='snmp_alerts_olt_id_ebf434_idx'),
        ),
        migrations.AddIndex(
            model_name='snmpalert',
            index=models.Index(fields=['severity'], name='snmp_alerts_severit_de387d_idx'),
        ),
    ]
