# Generated by Django 6.0.5 on 2026-05-17 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snmp_collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrichistory',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
