# Generated by Django 6.0.5 on 2026-05-10 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveNgLab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('lab_path', models.CharField(help_text='Chemin complet du lab dans EVE-NG (ex: /opt/unetlab/labs/mylab.unl)', max_length=500)),
                ('eve_ng_url', models.CharField(blank=True, help_text='URL spécifique (sinon config globale)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_stopped_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eve_ng_labs',
            },
        ),
        migrations.CreateModel(
            name='EveNgDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('node_id', models.IntegerField(help_text='ID attribué par EVE-NG')),
                ('image', models.CharField(blank=True, max_length=100)),
                ('cpu', models.IntegerField(default=1)),
                ('ram', models.IntegerField(default=1024, help_text='RAM en MB')),
                ('configuration', models.JSONField(default=dict, help_text='Configuration spécifique au nœud')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipements.devicetype')),
                ('olt', models.ForeignKey(blank=True, help_text='OLT réel associé (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipements.olt')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipements.vendor')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='eve_ng.evenglab')),
            ],
            options={
                'db_table': 'eve_ng_devices',
            },
        ),
        migrations.CreateModel(
            name='EveNgLabExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped')], max_length=20)),
                ('logs', models.TextField(blank=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='eve_ng.evenglab')),
            ],
            options={
                'db_table': 'eve_ng_lab_executions',
                'ordering': ['-started_at'],
            },
        ),
    ]
