# Generated by Django 6.0.5 on 2026-05-10 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('daily', 'Rapport quotidien'), ('weekly', 'Rapport hebdomadaire'), ('monthly', 'Rapport mensuel'), ('custom', 'Personnalisé')], max_length=10)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel')], default='pdf', max_length=10)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('generating', 'Génération en cours'), ('ready', 'Prêt'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/')),
                ('parameters', models.JSONField(default=dict, help_text='Filtres additionnels (olts, sites, etc.)')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('line_chart', 'Graphique linéaire'), ('bar_chart', 'Graphique à barres'), ('pie_chart', 'Camembert'), ('gauge', 'Jauge'), ('metric', 'Indicateur simple'), ('table', 'Tableau de données'), ('map', 'Carte géographique')], max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Couleurs, axes, métriques, etc.')),
                ('width', models.IntegerField(default=6, help_text='Colonnes (sur 12)')),
                ('height', models.IntegerField(default=300, help_text='Hauteur en pixels')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_dashboard_widgets',
                'ordering': ['user', 'order'],
                'unique_together': {('user', 'order')},
            },
        ),
        migrations.CreateModel(
            name='KPIHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(choices=[('hour', 'Horaire'), ('day', 'Journalier'), ('week', 'Hebdomadaire'), ('month', 'Mensuel')], db_index=True, max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('total_olts', models.IntegerField(default=0)),
                ('active_olts', models.IntegerField(default=0)),
                ('total_onts', models.IntegerField(default=0)),
                ('online_onts', models.IntegerField(default=0)),
                ('avg_cpu_usage', models.FloatField(blank=True, null=True)),
                ('avg_memory_usage', models.FloatField(blank=True, null=True)),
                ('avg_temperature', models.FloatField(blank=True, null=True)),
                ('avg_rx_power', models.FloatField(blank=True, null=True)),
                ('snmp_success_rate', models.FloatField(default=100.0)),
                ('bfd_up_sessions', models.IntegerField(default=0)),
                ('bfd_total_sessions', models.IntegerField(default=0)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('alert_count', models.IntegerField(default=0)),
                ('olt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.olt')),
            ],
            options={
                'db_table': 'analytics_kpi_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['period', 'timestamp'], name='analytics_k_period_0f6743_idx'), models.Index(fields=['olt', 'timestamp'], name='analytics_k_olt_id_8cee5b_idx')],
            },
        ),
    ]
