# Generated by Django 6.0.5 on 2026-05-14 21:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('equipements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du dispositif')),
                ('device_type', models.CharField(choices=[('olt', 'OLT'), ('switch', 'Switch'), ('router', 'Routeur'), ('firewall', 'Firewall')], max_length=20, verbose_name='Type')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='Adresse IP')),
                ('hostname', models.CharField(blank=True, max_length=100, verbose_name="Nom d'hôte")),
                ('auth_method', models.CharField(choices=[('ssh_password', 'SSH Mot de passe'), ('ssh_key', 'SSH Clé'), ('snmp', 'SNMP')], default='ssh_password', max_length=20, verbose_name='Méthode')),
                ('ssh_username', models.CharField(blank=True, max_length=100, verbose_name='Utilisateur SSH')),
                ('ssh_password', models.CharField(blank=True, max_length=200, verbose_name='Mot de passe SSH (chiffré)')),
                ('ssh_port', models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Port SSH')),
                ('ssh_key', models.TextField(blank=True, verbose_name='Clé privée SSH (optionnel)')),
                ('snmp_community', models.CharField(blank=True, default='public', max_length=100, verbose_name='Communauté SNMP')),
                ('snmp_port', models.IntegerField(default=161, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Port SNMP')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('is_reachable', models.BooleanField(default=False, verbose_name='Accessible')),
                ('last_connection_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('connection_error', models.TextField(blank=True, verbose_name='Erreur de connexion')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_devices', to='equipements.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Appareil réseau',
                'verbose_name_plural': 'Appareils réseau',
                'db_table': 'analytics_network_devices',
                'ordering': ['site', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Horodatage')),
                ('bytes_in', models.BigIntegerField(default=0, verbose_name='Bytes reçus')),
                ('bytes_out', models.BigIntegerField(default=0, verbose_name='Bytes envoyés')),
                ('packets_in', models.BigIntegerField(default=0, verbose_name='Paquets reçus')),
                ('packets_out', models.BigIntegerField(default=0, verbose_name='Paquets envoyés')),
                ('errors_in', models.IntegerField(default=0, verbose_name='Erreurs réception')),
                ('errors_out', models.IntegerField(default=0, verbose_name='Erreurs émission')),
                ('dropped_packets', models.IntegerField(default=0, verbose_name='Paquets perdus')),
                ('throughput_mbps', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Débit (Mbps)')),
                ('utilization_pct', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Utilisation (%)')),
                ('is_congested', models.BooleanField(default=False, verbose_name='Congestionné')),
                ('is_anomaly', models.BooleanField(db_index=True, default=False, verbose_name='Anomalie')),
                ('fiber_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traffic_metrics', to='equipements.fibrelink', verbose_name='Lien fibre')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traffic_metrics', to='equipements.networkinterface', verbose_name='Interface')),
            ],
            options={
                'verbose_name': 'Trafic réseau',
                'verbose_name_plural': 'Trafic réseau',
                'db_table': 'analytics_network_traffic',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SSHMetricsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Horodatage')),
                ('cpu_usage_pct', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Utilisation CPU (%)')),
                ('memory_usage_pct', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Utilisation mémoire (%)')),
                ('memory_available_mb', models.IntegerField(blank=True, null=True, verbose_name='Mémoire disponible (MB)')),
                ('temperature_c', models.FloatField(blank=True, null=True, verbose_name='Température (°C)')),
                ('temperature_threshold_c', models.FloatField(blank=True, null=True, verbose_name='Seuil température (°C)')),
                ('optical_rx_power_dbm', models.FloatField(blank=True, null=True, verbose_name='Puissance RX (dBm)')),
                ('optical_tx_power_dbm', models.FloatField(blank=True, null=True, verbose_name='Puissance TX (dBm)')),
                ('uptime_seconds', models.BigIntegerField(blank=True, null=True, verbose_name='Uptime (secondes)')),
                ('process_count', models.IntegerField(blank=True, null=True, verbose_name='Nombre de processus')),
                ('active_connections', models.IntegerField(blank=True, null=True, verbose_name='Connexions actives')),
                ('is_anomaly', models.BooleanField(db_index=True, default=False, verbose_name='Anomalie détectée')),
                ('collection_duration_ms', models.IntegerField(blank=True, null=True, verbose_name='Durée collecte (ms)')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_metrics', to='analytics.networkdevice', verbose_name='Appareil')),
            ],
            options={
                'verbose_name': 'Snapshot métriques SSH',
                'verbose_name_plural': 'Snapshots métriques SSH',
                'db_table': 'analytics_ssh_metrics_snapshots',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TopologyLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_interface', models.CharField(max_length=50, verbose_name='Interface source')),
                ('destination_interface', models.CharField(max_length=50, verbose_name='Interface destination')),
                ('link_type', models.CharField(choices=[('backbone', 'Backbone'), ('distribution', 'Distribution'), ('access', 'Accès'), ('internal', 'Interne')], default='backbone', max_length=20, verbose_name='Type')),
                ('bandwidth_mbps', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bande passante (Mbps)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('destination_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='analytics.networkdevice', verbose_name='Appareil destination')),
                ('source_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='analytics.networkdevice', verbose_name='Appareil source')),
            ],
            options={
                'verbose_name': 'Lien de topologie',
                'verbose_name_plural': 'Liens de topologie',
                'db_table': 'analytics_topology_links',
                'ordering': ['source_device', 'destination_device'],
            },
        ),
        migrations.AddIndex(
            model_name='networkdevice',
            index=models.Index(fields=['ip_address'], name='analytics_n_ip_addr_cc4a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='networkdevice',
            index=models.Index(fields=['site', 'is_active'], name='analytics_n_site_id_35a3a7_idx'),
        ),
        migrations.AddIndex(
            model_name='networktraffic',
            index=models.Index(fields=['timestamp', 'is_anomaly'], name='analytics_n_timesta_193d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='networktraffic',
            index=models.Index(fields=['interface', '-timestamp'], name='analytics_n_interfa_9653a6_idx'),
        ),
        migrations.AddIndex(
            model_name='networktraffic',
            index=models.Index(fields=['fiber_link', '-timestamp'], name='analytics_n_fiber_l_624413_idx'),
        ),
        migrations.AddIndex(
            model_name='sshmetricssnapshot',
            index=models.Index(fields=['device', '-timestamp'], name='analytics_s_device__001fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='sshmetricssnapshot',
            index=models.Index(fields=['timestamp', 'is_anomaly'], name='analytics_s_timesta_a8f5e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='topologylink',
            constraint=models.UniqueConstraint(fields=('source_device', 'source_interface', 'destination_device', 'destination_interface'), name='unique_topology_link'),
        ),
    ]
