# Generated by Django 6.0.5 on 2026-05-10 16:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipements', '0001_initial'),
        ('snmp_collector', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('model_type', models.CharField(choices=[('isolation_forest', 'Isolation Forest'), ('random_forest', 'Random Forest'), ('lstm', 'LSTM (deep learning)'), ('prophet', 'Prophet (prédiction série temporelle)'), ('grok', 'Grok (xAI)')], max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, help_text='Chemin du fichier modèle (pickle/joblib/h5)', max_length=500)),
                ('parameters', models.JSONField(default=dict, help_text='Hyperparamètres du modèle')),
                ('features', models.JSONField(default=list, help_text="Liste des features utilisées (noms d'OIDs ou métriques)")),
                ('target_metric', models.CharField(blank=True, help_text='Métrique cible pour les prédictions', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('training', 'Entraînement en cours'), ('active', 'Actif'), ('failed', 'Échec'), ('archived', 'Archivé')], default='pending', max_length=20)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('last_trained_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Modèle actif pour les inférences')),
                ('trained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_ml_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InferenceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('inference_time_ms', models.FloatField()),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.mlmodel')),
            ],
            options={
                'db_table': 'ai_inference_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('success', 'Succès'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('metrics', models.JSONField(default=dict, help_text="Métriques d'évaluation (accuracy, loss, etc.)")),
                ('error_message', models.TextField(blank=True)),
                ('data_start_date', models.DateTimeField(help_text="Début des données d'entraînement")),
                ('data_end_date', models.DateTimeField(help_text="Fin des données d'entraînement")),
                ('samples_count', models.IntegerField(default=0)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='ai_engine.mlmodel')),
            ],
            options={
                'db_table': 'ai_training_jobs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_name', models.CharField(help_text='Nom de la métrique (ex: cpu_usage)', max_length=200)),
                ('expected_value', models.FloatField(blank=True, null=True)),
                ('actual_value', models.FloatField()),
                ('anomaly_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('explanation', models.TextField(blank=True, help_text='Explication textuelle (ex: via Grok)')),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.networkinterface')),
                ('oid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snmp_collector.snmpoid')),
                ('olt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='equipements.olt')),
                ('ont', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='equipements.ont')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.mlmodel')),
            ],
            options={
                'db_table': 'ai_anomaly_detections',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['olt', '-detected_at'], name='ai_anomaly__olt_id_44a6a2_idx'), models.Index(fields=['severity'], name='ai_anomaly__severit_3dfc0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_name', models.CharField(max_length=200)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('prediction_time', models.DateTimeField(help_text='Horodatage de la prédiction (moment futur)')),
                ('predicted_value', models.FloatField()),
                ('lower_bound', models.FloatField(blank=True, null=True)),
                ('upper_bound', models.FloatField(blank=True, null=True)),
                ('confidence_interval', models.FloatField(default=0.95, help_text='Niveau de confiance')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.mlmodel')),
                ('olt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='equipements.olt')),
                ('ont', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='equipements.ont')),
            ],
            options={
                'db_table': 'ai_predictions',
                'ordering': ['-predicted_at'],
                'indexes': [models.Index(fields=['olt', 'prediction_time'], name='ai_predicti_olt_id_6c92a5_idx')],
            },
        ),
    ]
